import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <div>
            <Link href="/">
              <span>Y</span>
              <span>Yet another blog</span>
            </Link>
            <div>
              <input placeholder="Search articles, categories..."></input>
              <button>Search</button>
            </div>
            <nav>
              <Link href="/articles">Articles</Link>
              <Link href="/categories">Categories</Link>
              <Link href="/authors">Authors</Link>
              {/* Mobile menu */}
              {/* <button></button> */}
            </nav>
            <div>
              {/* For authorized users */}
              <button>Sign in</button>
              {/* For non authorized users */}
              {/* <button>Sign out</button>
              <span>Avatar</span> */}
            </div>
          </div>
        </header>
        {children}
        <footer>
          <div>© 2025 Yet another Blog — All rights reserved</div>
          <div>
            <Link href="/articles">Articles</Link>
            <Link href="/categories">Categories</Link>
            <Link href="/authors">Authors</Link>
            <Link href="/about">About</Link>
            <Link href="#">Twitter</Link>
            <Link href="#">Sitemap</Link>
          </div>
        </footer>
      </body>
    </html>
  )
}
